find_path(SDL2_IMAGE_INCLUDE_DIR SDL_image.h)
find_library(SDL2_IMAGE_LIBRARY NAMES SDL2_image)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SDL2_image DEFAULT_MSG SDL2_IMAGE_LIBRARY SDL2_IMAGE_INCLUDE_DIR)

if(SDL2_IMAGE_FOUND)
  set(SDL2_IMAGE_LIBRARIES ${SDL2_IMAGE_LIBRARY})
  set(SDL2_IMAGE_INCLUDE_DIRS ${SDL2_IMAGE_INCLUDE_DIR})
endif()

mark_as_advanced(SDL2_IMAGE_INCLUDE_DIR SDL2_IMAGE_LIBRARY)

